spring:
  sql:
    init:
      mode: always
  application:
    name=collector
  datasource:
    initialization-mode: always
    # url: jdbc:h2:tcp://localhost//home/bong/Desktop/work/h2db/h2_230
    url: jdbc:h2:tcp://localhost//home/bont/Desktop/work/h2/2.3.232/myDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 부팅 시 ddl 자동 생성
