DELETE FROM LIKES;
DELETE FROM ITEMS;
DELETE FROM USERS;

INSERT INTO USERS(USER_ID, LOGIN_ID, PASSWORD, ROLES) VALUES(1,'aa','$2a$10$dH5caaexAlKTwvR9gGe1/.Hu77lIkaB8hRNk/8/xoscPd6GmiZ5E2','admin');
INSERT INTO USERS(USER_ID, LOGIN_ID, PASSWORD, ROLES) VALUES(2,'admin','$2a$10$TIScLeW1UPYOHpTtLTdwzeTDJibG8QYgMVBRsnJWv8jv5cB80VZwa','ADMIN');